version: "3.9"
services:
  rabbitmq_server:
    restart: always
    container_name: rabbitmq_server
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass.123
      - RABBITMQ_ERLANG_COOKIE= yowkotest
    volumes:
      - /mnt/d/wsl_ubuntu/volumes_data/rabbitmq:/var/lib/rabbitmq
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
  redis_server:
    restart: always
    container_name: redis_server
    image: redis:7.4-alpine
    ports:
      - 10079:6379
    volumes:
      - /mnt/d/wsl_ubuntu/volumes_data/redis-data:/data
  db_server:
    image: postgres
    restart: always
    container_name: db_server
    volumes:
      - /mnt/d/wsl_ubuntu/volumes_data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres_n
      POSTGRES_PASSWORD: postgres_p
    ports:
      - 15433:5432
  fast_api_app:
    build:
      context: ./backend
    container_name: fast_api_app
    restart: always
    depends_on:
      - db_server
      - redis_server
      - rabbitmq_server
    volumes:
      - ./backend:/backend
    ports:
      - 9800:8800