[project]
name = "task04-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles==24.1.0",
    "dcm2niix>=1.0.20250506",
    "fastapi==0.115.0",
    "fastapi-cache2==0.2.2",
    "funboost==48.4",
    "httpx==0.28.0",
    "nibabel==5.3.0",
    "numba==0.61.0",
    "numpy==1.26.0",
    "openpyxl==3.1.5",
    "orjson>=3.11.3",
    "pandas==2.1.0",
    "persist-queue[extra]==1.0.0",
    "pgqueuer>=0.17.3",
    "pip>=25.2",
    "psutil==7.0.0",
    "pydantic==2.10.0",
    "pydantic-settings==2.6.0",
    "pydicom==2.4.3",
    "pydicom-seg==0.4.1",
    "pynvml>=13.0.1",
    "pyorthanc==1.22.1",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "pyyaml==6.0.2",
    "scikit-image>=0.25.0",
    "setuptools>=80.9.0",
    "simpleitk>=2.4.0",
    "tensorflow==2.14.1",
    "torch>=2.5.1",
    "torchaudio>=2.5.1",
    "torchvision>=0.20.1",
    "tqdm==4.67.0",
    "uvicorn[standard]==0.34.0",
    "wheel>=0.45.1",
    "pylibjpeg", "pylibjpeg-libjpeg", "pylibjpeg-libjpegls"
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
