# app/series/urls.py
SERIES_GET_HEALTH_CHECK              = "/series"
SERIES_GET_AVAILABLE_SERIES_TYPES    = f"{SERIES_GET_HEALTH_CHECK}/types"
SERIES_ANALYZE_DICOM_FILES_BY_PATH   = f"{SERIES_GET_HEALTH_CHECK}/dicom/analyze/by-path"
SERIES_ANALYZE_DICOM_FILES_BY_UPLOAD = f"{SERIES_GET_HEALTH_CHECK}/dicom/analyze/by-upload"
